[package]
name = "imageboard_downloader"
authors = ["Ferrah Aiko Wolf <ferrahwolfeh@proton.me>"]
version = "0.28.0"
edition = "2021"
description = "Cli utility to bulk download images from popular imageboard sites (Boorus) using their APIs"
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/FerrahWolfeh/imageboard-downloader-rs"
documentation = "https://docs.rs/imageboard_downloader"
keywords = ["download", "api", "e621", "danbooru", "rule34"]
categories = ["command-line-utilities", "multimedia::images"]
include = ["**/*.rs", "Cargo.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
serde_json = "1.0.83"
indicatif = "0.17.0"
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.60"
futures = "0.3.21"
tempdir = "0.3.7"
md5 = "0.7.0"
colored = "2.0.0"
thiserror = "1.0.32"
thiserror-impl = "1.0.32"
zstd = "0.11.2"
bincode = "1.3.3"
async-trait = "0.1.57"
bytes = "1.2.1"
directories = "4.0.1"

[dependencies.zip]
version = "0.6.2"
default-features = false
features = ["deflate", "time"]

[features]
default = ["global_blacklist"]
global_blacklist = ["toml"]

[dependencies.toml]
version = "0.5.9"
optional = true

[dependencies.ahash]
version = "0.8.0"
features = ["serde"]

[dependencies.tokio]
version = "1"
features = ["macros", "fs", "rt-multi-thread"]

[dependencies.reqwest]
version = "0.11.11"
default-features = false
features = ["json", "stream", "rustls-tls"]

[dependencies.clap]
version = "3.2.16"
features = ["derive", "cargo"]

[dependencies.serde]
version = "1.0.143"
features = ["derive"]

[profile.release]
lto = false
opt-level = 3
strip = true
debug = false

[profile.opttest]
inherits = "release"
lto = false
opt-level = 3
strip = false
debug = true
