[package]
name = "booru_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.83"
bincode = "1.3.3"
zstd = "0.11.2+zstd.1.5.2"
md5 = "0.7.0"
sha256 = "1.0.3"
indicatif = "0.17.0"
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.60"
futures = "0.3.21"
tempdir = "0.3.7"


[dependencies.tokio]
version = "1.20.1"
features = ["full"]

[dependencies.zip]
version = "0.6.2"
default-features = false

[dependencies.image]
version = "0.24.3"
features = ["avif"]

[dependencies.downloader]
version = "0.2.6"
features = ["tui"]

[dependencies.reqwest]
version = "0.11.11"
features = ["blocking", "json"]

[dependencies.clap]
version = "3.2.16"
features = ["derive", "cargo"]

[dependencies.serde]
version = "1.0.142"
features = ["derive"]
