[package]
name = "imageboard_downloader"
authors = ["Ferrah Aiko Wolf <ferrahwolfeh@proton.me>"]
version = "0.9.5"
edition = "2021"
description = "Cli utility to bulk download images from popular imageboard sites (Boorus) using their APIs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.83"
indicatif = "0.17.0"
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.60"
futures = "0.3.21"
tempdir = "0.3.7"
md5 = "0.7.0"
colored = "2.0.0"
xdg = "2.4.1"
bincode = "1.3.3"


[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.reqwest]
version = "0.11.11"
features = ["json", "stream"]

[dependencies.clap]
version = "3.2.16"
features = ["derive", "cargo"]

[dependencies.serde]
version = "1.0.143"
features = ["derive"]

[profile.release]
lto = true
opt-level = 3
strip = true
debug = false
