[package]
name = "ibdl-common"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
directories = "4.0.1"
md5 = "0.7.0"
colored = "2.0.0"
thiserror = "1.0.32"
thiserror-impl = "1.0.32"
serde_json = "1.0.83"
zstd = "0.11.2"
bincode = "1.3.3"

[dependencies.clap]
version = "3.2.16"
features = ["derive", "cargo"]

[dependencies.tokio]
version = "1"
features = ["macros", "fs", "rt-multi-thread"]

[dependencies.serde]
version = "1.0.143"
features = ["derive"]

[dependencies.ahash]
version = "0.8.0"
features = ["serde"]

[dependencies.reqwest]
version = "0.11.11"
default-features = false
features = ["json", "stream", "rustls-tls"]