[servers]

# [servers.danbooru]
# pretty_name ="Danbooru"                                 # Required
# server = "danbooru"                                     # Required
# base_url = "https://danbooru.donmai.us"                 # Required
# post_url = "https://danbooru.donmai.us/posts/"          # Optional
# post_list_url = "https://danbooru.donmai.us/posts.json" # Optional
# pool_idx_url = "https://danbooru.donmai.us/pools"       # Optional
# max_post_limit = 200                                    # Required
# auth_url = "https://danbooru.donmai.us/profile.json"    # Optional

[servers.gelbooru]
pretty_name = "Gelbooru"
server = "gelbooru"
base_url = "https://gelbooru.com"
post_url = "http://gelbooru.com/index.php?page=dapi&s=post&q=index&json=1"
post_list_url = "http://gelbooru.com/index.php?page=dapi&s=post&q=index&json=1"
max_post_limit = 100

# [servers.yandere]
# pretty_name = "Yande.re"
# server = "moebooru"
# base_url = "https://yande.re"
# post_list_url = "https://yande.re/post.json"
# max_post_limit = 100
